sudo: required
services:
    - docker

before_install:
    - docker build -t madhokkarun/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true madhokkarun/docker-react npm run test -- --coverage
    
